name = "skir_client"
version = "1.0.0"
gleam = ">= 1.5.0"

licences = ["MIT"]
description = "Skir client runtime library for Gleam"

repository = { type = "github", user = "gepheum", repo = "skir" }
links = [
	{ title = "Repository", href = "https://github.com/gepheum/skir" },
]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
