name: Deploy to Hex.pm

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Erlang and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          rebar3-version: "3"
          gleam-version: "1.12.0"

      - name: Download dependencies
        run: gleam deps download

      - name: Publish package
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
        run: gleam publish
